spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
      # 开发环境关闭缓存
   cache: false

mybatis:
    type-aliases-package: cn.guzt.boottest.dao
    mapper-locations: classpath:mapper/*.xml

# 通用mapper配置 https://mapperhelper.github.io
mapper:
    mappers:
        - cn.guzt.boottest.base.mapper.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
    supportMethodsArguments: false #支持通过 Mapper 接口参数来传递分页参数，默认值 false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
    params: count=countSql