server:
  port: 8081
  tomcat:
    max-threads: 500
    min-spare-threads: 20
    uri-encoding: UTF-8

logging:
  level:
    root: INFO
    cn.guzt.boottest.dao: INFO
  path: /logfile/javaee/
  file: boottest.log

spring:
    datasource:
        druid:
          name: test
          url: jdbc:mysql://127.0.0.1:3306/boottest?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: root123
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 120
          initialSize: 20
          maxWait: 60000
          minIdle: 5
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20

swagger:
  enabled: false
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 2.0.0.RELEASE
  base-package: cn.guzt.boottest.controller

myparamers:
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2